import {
  API,
  LIMITS,
  languageOptions,
  STORAGE_KEYS,
  TRANSLATION_CONFIG,
} from "../data";

export { API, LIMITS, languageOptions, STORAGE_KEYS, TRANSLATION_CONFIG };

export const OLLAMA_API_BASE_URL = API.OLLAMA_BASE_URL;
export const LLAMA_CPP_API_BASE_URL = API.LLAMA_CPP_BASE_URL;
export const LOCAL_STORAGE_INPUT_LANG_KEY = STORAGE_KEYS.INPUT_LANG;
export const LOCAL_STORAGE_OUTPUT_LANG_KEY = STORAGE_KEYS.OUTPUT_LANG;
export const OLLAMA_MODEL_STORAGE_KEY = STORAGE_KEYS.SELECTED_MODEL;
export const FAVORITE_OLLAMA_MODEL_KEY = STORAGE_KEYS.FAVORITE_MODEL;
export const translationSystemPrompt = TRANSLATION_CONFIG.SYSTEM_PROMPT;
export const { AI_PARAMS } = TRANSLATION_CONFIG;
