import {
  languageOptions,
  STORAGE_KEYS,
  API,
  LIMITS,
  TRANSLATION_CONFIG,
} from "../data";

export { languageOptions, STORAGE_KEYS, API, LIMITS, TRANSLATION_CONFIG };

export const MAX_INPUT_CHARACTERS = LIMITS.MAX_INPUT_CHARACTERS;
export const OLLAMA_API_BASE_URL = API.BASE_URL;
export const OLLAMA_CONNECTION_ERROR_PREFIX = API.CONNECTION_ERROR_PREFIX;
export const LOCAL_STORAGE_INPUT_LANG_KEY = STORAGE_KEYS.INPUT_LANG;
export const LOCAL_STORAGE_OUTPUT_LANG_KEY = STORAGE_KEYS.OUTPUT_LANG;
export const OLLAMA_MODEL_STORAGE_KEY = STORAGE_KEYS.SELECTED_MODEL;
export const FAVORITE_OLLAMA_MODEL_KEY = STORAGE_KEYS.FAVORITE_MODEL;
export const translationSystemPrompt = TRANSLATION_CONFIG.SYSTEM_PROMPT;
export const { AI_PARAMS } = TRANSLATION_CONFIG;
